# Generated by Django 3.2.6 on 2021-08-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('phoneNumber', models.IntegerField(max_length=10)),
                ('emailAddress', models.EmailField(max_length=500)),
                ('streetAddress', models.CharField(max_length=150)),
            ],
        ),
    ]
